name: Release
on: workflow_dispatch
jobs:
  Android:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Installing Libraries
        run: |
          haxelib install lime 8.1.0 --quiet
          haxelib install openfl 9.3.1 --quiet
          haxelib install flixel 5.4.1 --quiet
          haxelib install flixel-addons 3.2.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install hxluajit --quiet
          haxelib install hxvlc 2.0.1 --quiet
          haxelib install extension-androidtools 2.1.1 --quiet

      - name: Setup Git hxcpp
        run: |
          haxelib git hxcpp https://github.com/FunkinCrew/hxcpp
          haxelib run lime rebuild hxcpp

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Building
        run: haxelib run lime build android -release

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/android/bin/app/build/outputs/apk/debug
          if-no-files-found: warn
  Publish:
    needs: Android
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download
        uses: actions/download-artifact@main
        with:
           name: androidBuild
           path: ${{github.workspace}}

      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          prerelease: false
          automatic_release_tag: 'v1.0.0-android'
          title: 'Android Release 1.0.0'
          files: ${{github.workspace}}/ShaggyMod-debug.apk
